# Generated by Django 3.2.6 on 2021-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('drawing', models.ImageField(upload_to='images')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.DeleteModel(
            name='PortfolioPost',
        ),
    ]
