# Generated by Django 3.2.6 on 2021-09-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0006_alter_portfolio_artstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
