# Generated by Django 3.2.6 on 2021-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0007_alter_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='artstyle',
            field=models.IntegerField(choices=[(0, 'Charcoal'), (1, 'Photoshop'), (2, 'Painting'), (3, 'Reel'), (4, 'Sketching'), (5, 'Illustrator'), (6, 'Pet_Portraits')], default=2),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='drawing',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
