# Generated by Django 3.2.6 on 2021-09-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finearts', '0008_auto_20210927_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='artstyle',
            field=models.IntegerField(choices=[(0, 'Charcoal'), (1, 'Photoshop'), (2, 'Painting'), (4, 'Sketching'), (5, 'Illustrator'), (6, 'Pet_Portraits')], default=2),
        ),
    ]
